//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogixTool.Logix.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogixResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogixTool.Logix.Resources.LogixResources", typeof(LogixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DataTypes&gt;
        ///  &lt;DataType Name=&quot;ALARM&quot; Class=&quot;Predefined&quot; Size=&quot;96&quot; Mapped=&quot;true&quot;&gt;
        ///    &lt;Members&gt;
        ///      &lt;Member Name=&quot;EnableIn&quot; DataType=&quot;BOOL&quot; Dimension=&quot;0&quot; Radix=&quot;Decimal&quot; Hidden=&quot;false&quot; ExternalAccess=&quot;Read/Write&quot; Row=&quot;0&quot; Pos=&quot;0&quot; Length=&quot;1&quot;/&gt;
        ///      &lt;Member Name=&quot;In&quot; DataType=&quot;REAL&quot; Dimension=&quot;0&quot; Radix=&quot;Float&quot; Hidden=&quot;false&quot; ExternalAccess=&quot;Read/Write&quot; Row=&quot;1&quot; Pos=&quot;0&quot; Length=&quot;32&quot;/&gt;
        ///      &lt;Member Name=&quot;HHLimit&quot; DataType=&quot;REAL&quot; Dimension=&quot;0&quot; Radix=&quot;Float&quot; Hidden=&quot;fa [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string PredefinedDataTypes {
            get {
                return ResourceManager.GetString("PredefinedDataTypes", resourceCulture);
            }
        }
    }
}
